language: node_js

node_js:
  - "0.10"

services:
  - mongodb

script: "grunt mongo:populate"

addons:
  code_climate:
    repo_token:
      secure: "hrUanDfyczomvyEYHJI9iQ39eVLyk1c4UjNHfa5Ea/gmaIhIUt94tUMDnU2fMQfNhXdNV+3WPeguMh5HGyLT5z7hPUPMDbXR+qELTPajTgxM+5e1BB199seMt9CIC/oa5L8a3wAKcZoX5N/Yo7rz9BoCFK1cbgoXhJzxSQunDGs="

after_script:
  - cat test/coverage/reports/lcov.info | codeclimate
